[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
FranklinTemplates = "3a985190-f512-4703-8d38-2a7944ed5916"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
